// Verifies the signed-manifest logic of updater.js against the manifest generated by build.mjs.
"use strict";
const Module = require("node:module");
const orig = Module._load;
Module._load = function (req, ...rest) {
  if (req === "electron") return { app: { getPath: () => "/tmp/x", getVersion: () => "0.0.0" }, dialog: {}, shell: {}, Notification: class {} };
  return orig.call(this, req, ...rest);
};
const { verifyManifest, isTemporaryLocation } = require("./updater.js");
const fs = require("node:fs");
const src = fs.readFileSync(require.resolve("../lib/desktop-release.ts"), "utf8");
const manifest = JSON.parse(/export const manifest = (".*");/.exec(src)[1]);
const signature = JSON.parse(/export const signature = (".*");/.exec(src)[1]);
const rel = verifyManifest({ signed: { manifest, signature } });
console.log("ok   signed manifest verifies:", rel.version, Object.keys(rel.assets).join(","));
for (const [name, bad] of [
  ["tampered version", { signed: { manifest: manifest.replace(rel.version, "9.9.9"), signature } }],
  ["tampered url", { signed: { manifest: manifest.replace("vercel-storage.com", "evil.example"), signature } }],
  ["no signature", { version: "9.9.9", assets: {} }],
  ["wrong signature", { signed: { manifest, signature: Buffer.alloc(64).toString("base64") } }],
]) {
  try { verifyManifest(bad); console.log("FAIL accepted", name); process.exit(1); } catch (e) { console.log("ok   rejected", name, "->", e.message); }
}
console.log("ok   translocation detected:", isTemporaryLocation("/private/var/folders/47/x/T/AppTranslocation/1B3E/d/Inline Autocorrect 2.app") === true, isTemporaryLocation("/Applications/Inline Autocorrect.app") === false);
console.log("ok   windows temp detected:", isTemporaryLocation("C:\\Users\\a\\AppData\\Local\\Temp\\Rar$EX\\Inline Autocorrect", "win32") === true, isTemporaryLocation("C:\\Users\\a\\AppData\\Local\\Programs\\Inline Autocorrect", "win32") === false);
